export const employeesTableData = [
  {
    id: 1,
    employeeCode: 'EMP001',
    title: 'Mr',
    firstName: 'John',
    middleName: 'A',
    lastName: 'Doe',
    employeeType: 'Full-time',
    status: 'Active',
    company: 'Tech Corp',
    businessUnit: 'IT',
    department: 'Development',
    territory: 'North',
    zone: 'East',
    region: 'NA',
    area: 'Metro',
    cluster: 'A1',
    branch: 'Main',
    branchCode: 'BR001',
    cityClassification: 'Tier 1',
    state: 'California',
    dateOfJoining: '2020-01-15',
    groupDOJ: '2020-01',
    grade: 'G5',
    band: 'B2',
    designation: 'Senior Developer',
    employeeCategory: 'Technical',
    employeeCategoryType: 'Permanent',
    l1ManagerCode: 'MGR001',
    l1Manager: 'Alice Smith',
    l2ManagerCode: 'MGR002',
    l2Manager: 'Bob Johnson',
    hrManagerCode: 'HR001',
    hrManager: 'Carol Williams',
    functionHead: 'David Brown',
    practiceHead: 'Eve Davis',
    jobRole: 'Software Development'
  },
  {
    id: 2,
    employeeCode: 'EMP002',
    title: 'Ms',
    firstName: 'Jane',
    middleName: '',
    lastName: 'Smith',
    employeeType: 'Part-time',
    status: 'Active',
    company: 'Tech Corp',
    businessUnit: 'HR',
    department: 'Recruitment',
    territory: 'South',
    zone: 'West',
    region: 'NA',
    area: 'Urban',
    cluster: 'B2',
    branch: 'West',
    branchCode: 'BR002',
    cityClassification: 'Tier 2',
    state: 'Texas',
    dateOfJoining: '2021-03-10',
    groupDOJ: '2021-03',
    grade: 'G4',
    band: 'B1',
    designation: 'HR Specialist',
    employeeCategory: 'Administrative',
    employeeCategoryType: 'Permanent',
    l1ManagerCode: 'MGR003',
    l1Manager: 'Frank Wilson',
    l2ManagerCode: 'MGR004',
    l2Manager: 'Grace Lee',
    hrManagerCode: 'HR002',
    hrManager: 'Henry Moore',
    functionHead: 'Ivy Chen',
    practiceHead: 'Jack Taylor',
    jobRole: 'Talent Acquisition'
  },
  {
    id: 3,
    employeeCode: 'EMP003',
    title: 'Mr',
    firstName: 'Michael',
    middleName: 'B',
    lastName: 'Johnson',
    employeeType: 'Full-time',
    status: 'Active',
    company: 'Tech Corp',
    businessUnit: 'Sales',
    department: 'Business Development',
    territory: 'East',
    zone: 'Central',
    region: 'NA',
    area: 'Suburban',
    cluster: 'C3',
    branch: 'East',
    branchCode: 'BR003',
    cityClassification: 'Tier 1',
    state: 'New York',
    dateOfJoining: '2019-06-22',
    groupDOJ: '2019-06',
    grade: 'G6',
    band: 'B3',
    designation: 'Sales Manager',
    employeeCategory: 'Sales',
    employeeCategoryType: 'Permanent',
    l1ManagerCode: 'MGR005',
    l1Manager: 'Karen White',
    l2ManagerCode: 'MGR006',
    l2Manager: 'Liam Brown',
    hrManagerCode: 'HR003',
    hrManager: 'Mia Davis',
    functionHead: 'Noah Clark',
    practiceHead: 'Olivia Green',
    jobRole: 'Sales Leadership'
  },
  {
    id: 4,
    employeeCode: 'EMP004',
    title: 'Ms',
    firstName: 'Emily',
    middleName: 'C',
    lastName: 'Davis',
    employeeType: 'Contract',
    status: 'Active',
    company: 'Tech Corp',
    businessUnit: 'IT',
    department: 'Quality Assurance',
    territory: 'West',
    zone: 'South',
    region: 'NA',
    area: 'Rural',
    cluster: 'D4',
    branch: 'South',
    branchCode: 'BR004',
    cityClassification: 'Tier 3',
    state: 'Arizona',
    dateOfJoining: '2022-09-01',
    groupDOJ: '2022-09',
    grade: 'G3',
    band: 'B1',
    designation: 'QA Analyst',
    employeeCategory: 'Technical',
    employeeCategoryType: 'Temporary',
    l1ManagerCode: 'MGR007',
    l1Manager: 'Peter Adams',
    l2ManagerCode: 'MGR008',
    l2Manager: 'Quinn Taylor',
    hrManagerCode: 'HR004',
    hrManager: 'Rachel Lee',
    functionHead: 'Samuel King',
    practiceHead: 'Tara Moore',
    jobRole: 'Software Testing'
  },
  {
    id: 5,
    employeeCode: 'EMP005',
    title: 'Mr',
    firstName: 'Robert',
    middleName: '',
    lastName: 'Wilson',
    employeeType: 'Full-time',
    status: 'Inactive',
    company: 'Tech Corp',
    businessUnit: 'Finance',
    department: 'Accounting',
    territory: 'North',
    zone: 'West',
    region: 'NA',
    area: 'Metro',
    cluster: 'E5',
    branch: 'North',
    branchCode: 'BR005',
    cityClassification: 'Tier 1',
    state: 'Washington',
    dateOfJoining: '2018-11-30',
    groupDOJ: '2018-11',
    grade: 'G7',
    band: 'B4',
    designation: 'Finance Lead',
    employeeCategory: 'Finance',
    employeeCategoryType: 'Permanent',
    l1ManagerCode: 'MGR009',
    l1Manager: 'Uma Patel',
    l2ManagerCode: 'MGR010',
    l2Manager: 'Victor Singh',
    hrManagerCode: 'HR005',
    hrManager: 'Wendy Chen',
    functionHead: 'Xander Brooks',
    practiceHead: 'Yara Khan',
    jobRole: 'Financial Management'
  },
  {
    id: 6,
    employeeCode: 'EMP006',
    title: 'Ms',
    firstName: 'Sarah',
    middleName: 'D',
    lastName: 'Miller',
    employeeType: 'Part-time',
    status: 'Active',
    company: 'Tech Corp',
    businessUnit: 'Marketing',
    department: 'Digital Marketing',
    territory: 'South',
    zone: 'East',
    region: 'NA',
    area: 'Urban',
    cluster: 'F6',
    branch: 'Central',
    branchCode: 'BR006',
    cityClassification: 'Tier 2',
    state: 'Florida',
    dateOfJoining: '2023-02-14',
    groupDOJ: '2023-02',
    grade: 'G4',
    band: 'B2',
    designation: 'Marketing Specialist',
    employeeCategory: 'Marketing',
    employeeCategoryType: 'Permanent',
    l1ManagerCode: 'MGR011',
    l1Manager: 'Zoe Carter',
    l2ManagerCode: 'MGR012',
    l2Manager: 'Adam Scott',
    hrManagerCode: 'HR006',
    hrManager: 'Bella Evans',
    functionHead: 'Chris Ford',
    practiceHead: 'Diana Gray',
    jobRole: 'Digital Campaigns'
  },
  {
    id: 7,
    employeeCode: 'EMP007',
    title: 'Mr',
    firstName: 'Thomas',
    middleName: 'E',
    lastName: 'Brown',
    employeeType: 'Full-time',
    status: 'Active',
    company: 'Tech Corp',
    businessUnit: 'Operations',
    department: 'Logistics',
    territory: 'Central',
    zone: 'North',
    region: 'NA',
    area: 'Suburban',
    cluster: 'G7',
    branch: 'Midwest',
    branchCode: 'BR007',
    cityClassification: 'Tier 2',
    state: 'Illinois',
    dateOfJoining: '2021-07-19',
    groupDOJ: '2021-07',
    grade: 'G5',
    band: 'B3',
    designation: 'Operations Manager',
    employeeCategory: 'Operations',
    employeeCategoryType: 'Permanent',
    l1ManagerCode: 'MGR013',
    l1Manager: 'Ella Hayes',
    l2ManagerCode: 'MGR014',
    l2Manager: 'Finn Walker',
    hrManagerCode: 'HR007',
    hrManager: 'Gina Ortiz',
    functionHead: 'Hank Price',
    practiceHead: 'Iris Reed',
    jobRole: 'Supply Chain Management'
  }
]
