export const employeesTableData = [
  {
    id: 1,
    employeeCode: 'EMP001',
    title: 'Mr',
    firstName: 'John',
    middleName: 'A',
    lastName: 'Doe',
    employeeType: 'Full-time',
    status: 'Active',
    company: 'Tech Corp',
    businessUnit: 'IT',
    department: 'Development',
    territory: 'North',
    zone: 'East',
    region: 'NA',
    area: 'Metro',
    cluster: 'A1',
    branch: 'Main',
    branchCode: 'BR001',
    cityClassification: 'Tier 1',
    state: 'California',
    dateOfJoining: '2020-01-15',
    groupDOJ: '2020-01',
    grade: 'G5',
    band: 'B2',
    designation: 'Senior Developer',
    employeeCategory: 'Technical',
    employeeCategoryType: 'Permanent',
    l1ManagerCode: 'MGR001',
    l1Manager: 'Alice Smith',
    l2ManagerCode: 'MGR002',
    l2Manager: 'Bob Johnson',
    hrManagerCode: 'HR001',
    hrManager: 'Carol Williams',
    functionHead: 'David Brown',
    practiceHead: 'Eve Davis',
    jobRole: 'Software Development',
    dateOfBirth: '1985-06-20',
    gender: 'Male',
    maritalStatus: 'Married',
    personalEmailAddress: 'john.doe@gmail.com',
    officialEmailAddress: 'john.doe@techcorp.com',
    confirmationStatus: 'Confirmed',
    residenceAddressLine1: '123 Main St',
    residenceState: 'California',
    residenceCity: 'San Francisco',
    residenceCountry: 'USA',
    residencePostalCode: '94105',
    residenceLandline: '-',
    bloodGroup: 'O+',
    confirmationDate: '2020-07-15',
    emergencyContactName: 'Jane Doe',
    emergencyContactRelation: 'Spouse',
    emergencyContactMobilePhone: '+1-555-123-4567',
    pfAccountNumber: 'PF123456',
    panNumber: 'ABCDE1234F',
    bankName: 'Bank of America',
    bankAccountNumber: '123456789012',
    ifscCode: 'BOFA0001234',
    uanNumber: '100123456789',
    noticePeriod: '60 days',
    mobileNumber: '+1-555-987-6543',
    dateOfResignation: '-',
    finalApprovalLWD: '-',
    foodCardNumber: 'FC123456',
    npsAccountNumber: 'NPS123456',
    esiNo: '-',
    isDisability: false,
    typeOfDisability: '-',
    nameAsPerAadhar: 'John A Doe',
    functionalManager: 'David Brown',
    totalExperience: '10 years',
    age: '39:11',
    retirementDate: '2045-06-20',
    pfApplicable: true,
    pfGrossLimit: '15000',
    lwfApplicable: false,
    esiApplicable: false,
    aadharNumber: '1234-5678-9012'
  },
  {
    id: 2,
    employeeCode: 'EMP002',
    title: 'Ms',
    firstName: 'Jane',
    middleName: '',
    lastName: 'Smith',
    employeeType: 'Part-time',
    status: 'Active',
    company: 'Tech Corp',
    businessUnit: 'HR',
    department: 'Recruitment',
    territory: 'South',
    zone: 'West',
    region: 'NA',
    area: 'Urban',
    cluster: 'B2',
    branch: 'West',
    branchCode: 'BR002',
    cityClassification: 'Tier 2',
    state: 'Texas',
    dateOfJoining: '2021-03-10',
    groupDOJ: '2021-03',
    grade: 'G4',
    band: 'B1',
    designation: 'HR Specialist',
    employeeCategory: 'Administrative',
    employeeCategoryType: 'Permanent',
    l1ManagerCode: 'MGR003',
    l1Manager: 'Frank Wilson',
    l2ManagerCode: 'MGR004',
    l2Manager: 'Grace Lee',
    hrManagerCode: 'HR002',
    hrManager: 'Henry Moore',
    functionHead: 'Ivy Chen',
    practiceHead: 'Jack Taylor',
    jobRole: 'Talent Acquisition',
    dateOfBirth: '1990-04-15',
    gender: 'Female',
    maritalStatus: 'Single',
    personalEmailAddress: 'jane.smith@gmail.com',
    officialEmailAddress: 'jane.smith@techcorp.com',
    confirmationStatus: 'Confirmed',
    residenceAddressLine1: '456 Oak Ave',
    residenceState: 'Texas',
    residenceCity: 'Austin',
    residenceCountry: 'USA',
    residencePostalCode: '73301',
    residenceLandline: '-',
    bloodGroup: 'A+',
    confirmationDate: '2021-09-10',
    emergencyContactName: 'Mary Smith',
    emergencyContactRelation: 'Mother',
    emergencyContactMobilePhone: '+1-555-234-5678',
    pfAccountNumber: 'PF789012',
    panNumber: 'FGHIJ5678K',
    bankName: 'Chase Bank',
    bankAccountNumber: '987654321098',
    ifscCode: 'CHAS0005678',
    uanNumber: '100987654321',
    noticePeriod: '30 days',
    mobileNumber: '+1-555-876-5432',
    dateOfResignation: '-',
    finalApprovalLWD: '-',
    foodCardNumber: 'FC789012',
    npsAccountNumber: 'NPS789012',
    esiNo: '-',
    isDisability: false,
    typeOfDisability: '-',
    nameAsPerAadhar: 'Jane Smith',
    functionalManager: 'Ivy Chen',
    totalExperience: '5 years',
    age: '34:01',
    retirementDate: '2055-04-15',
    pfApplicable: true,
    pfGrossLimit: '15000',
    lwfApplicable: false,
    esiApplicable: false,
    aadharNumber: '5678-9012-3456'
  },
  {
    id: 3,
    employeeCode: 'EMP003',
    title: 'Mr',
    firstName: 'Michael',
    middleName: 'B',
    lastName: 'Johnson',
    employeeType: 'Full-time',
    status: 'Active',
    company: 'Tech Corp',
    businessUnit: 'Sales',
    department: 'Business Development',
    territory: 'East',
    zone: 'Central',
    region: 'NA',
    area: 'Suburban',
    cluster: 'C3',
    branch: 'East',
    branchCode: 'BR003',
    cityClassification: 'Tier 1',
    state: 'New York',
    dateOfJoining: '2019-06-22',
    groupDOJ: '2019-06',
    grade: 'G6',
    band: 'B3',
    designation: 'Sales Manager',
    employeeCategory: 'Sales',
    employeeCategoryType: 'Permanent',
    l1ManagerCode: 'MGR005',
    l1Manager: 'Karen White',
    l2ManagerCode: 'MGR006',
    l2Manager: 'Liam Brown',
    hrManagerCode: 'HR003',
    hrManager: 'Mia Davis',
    functionHead: 'Noah Clark',
    practiceHead: 'Olivia Green',
    jobRole: 'Sales Leadership',
    dateOfBirth: '1978-09-10',
    gender: 'Male',
    maritalStatus: 'Married',
    personalEmailAddress: 'michael.johnson@gmail.com',
    officialEmailAddress: 'michael.johnson@techcorp.com',
    confirmationStatus: 'Confirmed',
    residenceAddressLine1: '789 Pine Rd',
    residenceState: 'New York',
    residenceCity: 'New York City',
    residenceCountry: 'USA',
    residencePostalCode: '10001',
    residenceLandline: '-',
    bloodGroup: 'B+',
    confirmationDate: '2019-12-22',
    emergencyContactName: 'Lisa Johnson',
    emergencyContactRelation: 'Spouse',
    emergencyContactMobilePhone: '+1-555-345-6789',
    pfAccountNumber: 'PF345678',
    panNumber: 'KLMNO9012P',
    bankName: 'Wells Fargo',
    bankAccountNumber: '345678901234',
    ifscCode: 'WFBI0009012',
    uanNumber: '100345678901',
    noticePeriod: '90 days',
    mobileNumber: '+1-555-765-4321',
    dateOfResignation: '-',
    finalApprovalLWD: '-',
    foodCardNumber: 'FC345678',
    npsAccountNumber: 'NPS345678',
    esiNo: '-',
    isDisability: false,
    typeOfDisability: '-',
    nameAsPerAadhar: 'Michael B Johnson',
    functionalManager: 'Noah Clark',
    totalExperience: '15 years',
    age: '46:08',
    retirementDate: '2038-09-10',
    pfApplicable: true,
    pfGrossLimit: '15000',
    lwfApplicable: false,
    esiApplicable: false,
    aadharNumber: '9012-3456-7890'
  },
  {
    id: 4,
    employeeCode: 'EMP004',
    title: 'Ms',
    firstName: 'Emily',
    middleName: 'C',
    lastName: 'Davis',
    employeeType: 'Contract',
    status: 'Active',
    company: 'Tech Corp',
    businessUnit: 'IT',
    department: 'Quality Assurance',
    territory: 'West',
    zone: 'South',
    region: 'NA',
    area: 'Rural',
    cluster: 'D4',
    branch: 'South',
    branchCode: 'BR004',
    cityClassification: 'Tier 3',
    state: 'Arizona',
    dateOfJoining: '2022-09-01',
    groupDOJ: '2022-09',
    grade: 'G3',
    band: 'B1',
    designation: 'QA Analyst',
    employeeCategory: 'Technical',
    employeeCategoryType: 'Temporary',
    l1ManagerCode: 'MGR007',
    l1Manager: 'Peter Adams',
    l2ManagerCode: 'MGR008',
    l2Manager: 'Quinn Taylor',
    hrManagerCode: 'HR004',
    hrManager: 'Rachel Lee',
    functionHead: 'Samuel King',
    practiceHead: 'Tara Moore',
    jobRole: 'Software Testing',
    dateOfBirth: '1995-02-25',
    gender: 'Female',
    maritalStatus: 'Single',
    personalEmailAddress: 'emily.davis@gmail.com',
    officialEmailAddress: 'emily.davis@techcorp.com',
    confirmationStatus: 'Not Confirmed',
    residenceAddressLine1: '101 Desert Ln',
    residenceState: 'Arizona',
    residenceCity: 'Phoenix',
    residenceCountry: 'USA',
    residencePostalCode: '85001',
    residenceLandline: '-',
    bloodGroup: 'AB+',
    confirmationDate: '-',
    emergencyContactName: 'Tom Davis',
    emergencyContactRelation: 'Father',
    emergencyContactMobilePhone: '+1-555-456-7890',
    pfAccountNumber: '-',
    panNumber: 'PQRST3456U',
    bankName: 'Bank of Arizona',
    bankAccountNumber: '567890123456',
    ifscCode: 'BOAZ0003456',
    uanNumber: '-',
    noticePeriod: '30 days',
    mobileNumber: '+1-555-654-3210',
    dateOfResignation: '-',
    finalApprovalLWD: '-',
    foodCardNumber: '-',
    npsAccountNumber: '-',
    esiNo: '-',
    isDisability: false,
    typeOfDisability: '-',
    nameAsPerAadhar: 'Emily C Davis',
    functionalManager: 'Samuel King',
    totalExperience: '3 years',
    age: '29:03',
    retirementDate: '2060-02-25',
    pfApplicable: false,
    pfGrossLimit: '-',
    lwfApplicable: false,
    esiApplicable: false,
    aadharNumber: '3456-7890-1234'
  },
  {
    id: 5,
    employeeCode: 'EMP005',
    title: 'Mr',
    firstName: 'Robert',
    middleName: '',
    lastName: 'Wilson',
    employeeType: 'Full-time',
    status: 'Inactive',
    company: 'Tech Corp',
    businessUnit: 'Finance',
    department: 'Accounting',
    territory: 'North',
    zone: 'West',
    region: 'NA',
    area: 'Metro',
    cluster: 'E5',
    branch: 'North',
    branchCode: 'BR005',
    cityClassification: 'Tier 1',
    state: 'Washington',
    dateOfJoining: '2018-11-30',
    groupDOJ: '2018-11',
    grade: 'G7',
    band: 'B4',
    designation: 'Finance Lead',
    employeeCategory: 'Finance',
    employeeCategoryType: 'Permanent',
    l1ManagerCode: 'MGR009',
    l1Manager: 'Uma Patel',
    l2ManagerCode: 'MGR010',
    l2Manager: 'Victor Singh',
    hrManagerCode: 'HR005',
    hrManager: 'Wendy Chen',
    functionHead: 'Xander Brooks',
    practiceHead: 'Yara Khan',
    jobRole: 'Financial Management',
    dateOfBirth: '1975-12-05',
    gender: 'Male',
    maritalStatus: 'Married',
    personalEmailAddress: 'robert.wilson@gmail.com',
    officialEmailAddress: 'robert.wilson@techcorp.com',
    confirmationStatus: 'Confirmed',
    residenceAddressLine1: '202 River Dr',
    residenceState: 'Washington',
    residenceCity: 'Seattle',
    residenceCountry: 'USA',
    residencePostalCode: '98101',
    residenceLandline: '-',
    bloodGroup: 'O-',
    confirmationDate: '2019-05-30',
    emergencyContactName: 'Susan Wilson',
    emergencyContactRelation: 'Spouse',
    emergencyContactMobilePhone: '+1-555-567-8901',
    pfAccountNumber: 'PF901234',
    panNumber: 'VWXYZ7890W',
    bankName: 'US Bank',
    bankAccountNumber: '789012345678',
    ifscCode: 'USBA0007890',
    uanNumber: '100789012345',
    noticePeriod: '90 days',
    mobileNumber: '+1-555-543-2109',
    dateOfResignation: '2023-12-01',
    finalApprovalLWD: '2024-02-29',
    foodCardNumber: 'FC901234',
    npsAccountNumber: 'NPS901234',
    esiNo: '-',
    isDisability: false,
    typeOfDisability: '-',
    nameAsPerAadhar: 'Robert Wilson',
    functionalManager: 'Xander Brooks',
    totalExperience: '20 years',
    age: '49:05',
    retirementDate: '2035-12-05',
    pfApplicable: true,
    pfGrossLimit: '15000',
    lwfApplicable: false,
    esiApplicable: false,
    aadharNumber: '7890-1234-5678'
  },
  {
    id: 6,
    employeeCode: 'EMP006',
    title: 'Ms',
    firstName: 'Sarah',
    middleName: 'D',
    lastName: 'Miller',
    employeeType: 'Part-time',
    status: 'Active',
    company: 'Tech Corp',
    businessUnit: 'Marketing',
    department: 'Digital Marketing',
    territory: 'South',
    zone: 'East',
    region: 'NA',
    area: 'Urban',
    cluster: 'F6',
    branch: 'Central',
    branchCode: 'BR006',
    cityClassification: 'Tier 2',
    state: 'Florida',
    dateOfJoining: '2023-02-14',
    groupDOJ: '2023-02',
    grade: 'G4',
    band: 'B2',
    designation: 'Marketing Specialist',
    employeeCategory: 'Marketing',
    employeeCategoryType: 'Permanent',
    l1ManagerCode: 'MGR011',
    l1Manager: 'Zoe Carter',
    l2ManagerCode: 'MGR012',
    l2Manager: 'Adam Scott',
    hrManagerCode: 'HR006',
    hrManager: 'Bella Evans',
    functionHead: 'Chris Ford',
    practiceHead: 'Diana Gray',
    jobRole: 'Digital Campaigns',
    dateOfBirth: '1992-07-30',
    gender: 'Female',
    maritalStatus: 'Married',
    personalEmailAddress: 'sarah.miller@gmail.com',
    officialEmailAddress: 'sarah.miller@techcorp.com',
    confirmationStatus: 'Confirmed',
    residenceAddressLine1: '303 Beach Blvd',
    residenceState: 'Florida',
    residenceCity: 'Miami',
    residenceCountry: 'USA',
    residencePostalCode: '33101',
    residenceLandline: '-',
    bloodGroup: 'A-',
    confirmationDate: '2023-08-14',
    emergencyContactName: 'Mark Miller',
    emergencyContactRelation: 'Spouse',
    emergencyContactMobilePhone: '+1-555-678-9012',
    pfAccountNumber: 'PF567890',
    panNumber: 'ABCDE2345X',
    bankName: 'SunTrust Bank',
    bankAccountNumber: '901234567890',
    ifscCode: 'SUNB0002345',
    uanNumber: '100901234567',
    noticePeriod: '30 days',
    mobileNumber: '+1-555-432-1098',
    dateOfResignation: '-',
    finalApprovalLWD: '-',
    foodCardNumber: 'FC567890',
    npsAccountNumber: 'NPS567890',
    esiNo: '-',
    isDisability: false,
    typeOfDisability: '-',
    nameAsPerAadhar: 'Sarah D Miller',
    functionalManager: 'Chris Ford',
    totalExperience: '4 years',
    age: '32:10',
    retirementDate: '2057-07-30',
    pfApplicable: true,
    pfGrossLimit: '15000',
    lwfApplicable: false,
    esiApplicable: false,
    aadharNumber: '1234-5678-9012'
  },
  {
    id: 7,
    employeeCode: 'EMP007',
    title: 'Mr',
    firstName: 'Thomas',
    middleName: 'E',
    lastName: 'Brown',
    employeeType: 'Full-time',
    status: 'Active',
    company: 'Tech Corp',
    businessUnit: 'Operations',
    department: 'Logistics',
    territory: 'Central',
    zone: 'North',
    region: 'NA',
    area: 'Suburban',
    cluster: 'G7',
    branch: 'Midwest',
    branchCode: 'BR007',
    cityClassification: 'Tier 2',
    state: 'Illinois',
    dateOfJoining: '2021-07-19',
    groupDOJ: '2021-07',
    grade: 'G5',
    band: 'B3',
    designation: 'Operations Manager',
    employeeCategory: 'Operations',
    employeeCategoryType: 'Permanent',
    l1ManagerCode: 'MGR013',
    l1Manager: 'Ella Hayes',
    l2ManagerCode: 'MGR014',
    l2Manager: 'Finn Walker',
    hrManagerCode: 'HR007',
    hrManager: 'Gina Ortiz',
    functionHead: 'Hank Price',
    practiceHead: 'Iris Reed',
    jobRole: 'Supply Chain Management',
    dateOfBirth: '1988-03-12',
    gender: 'Male',
    maritalStatus: 'Single',
    personalEmailAddress: 'thomas.brown@gmail.com',
    officialEmailAddress: 'thomas.brown@techcorp.com',
    confirmationStatus: 'Confirmed',
    residenceAddressLine1: '404 Lake St',
    residenceState: 'Illinois',
    residenceCity: 'Chicago',
    residenceCountry: 'USA',
    residencePostalCode: '60601',
    residenceLandline: '-',
    bloodGroup: 'B-',
    confirmationDate: '2022-01-19',
    emergencyContactName: 'Laura Brown',
    emergencyContactRelation: 'Sister',
    emergencyContactMobilePhone: '+1-555-789-0123',
    pfAccountNumber: 'PF234567',
    panNumber: 'FGHIJ6789Y',
    bankName: 'PNC Bank',
    bankAccountNumber: '234567890123',
    ifscCode: 'PNCB0006789',
    uanNumber: '100234567890',
    noticePeriod: '60 days',
    mobileNumber: '+1-555-321-0987',
    dateOfResignation: '-',
    finalApprovalLWD: '-',
    foodCardNumber: 'FC234567',
    npsAccountNumber: 'NPS234567',
    esiNo: '-',
    isDisability: true,
    typeOfDisability: 'Visual Impairment',
    nameAsPerAadhar: 'Thomas E Brown',
    functionalManager: 'Hank Price',
    totalExperience: '8 years',
    age: '36:02',
    retirementDate: '2048-03-12',
    pfApplicable: true,
    pfGrossLimit: '15000',
    lwfApplicable: false,
    esiApplicable: false,
    aadharNumber: '5678-9012-3456'
  }
]
