export const vacancyList = [
  {
    id: 1,
    designationName: 'Software Engineer',
    jobType: 'Full-time',
    vacancyPositions: 2,
    numberOfOpenings: 5,
    branch: 'IT Department',
    grade: 'A',
    band: 'Band3',
    noOfFilledPositions: 3,
    noOfApplicants: 73,
    shortlisted: 30,
    city: 'New York',
    experience: 3,
    createdAt: '2024-01-15',
    updatedAt: '2024-02-15',
    contactPerson: 'John Doe',
    status: 'Open' // Possible values: Open, Closed, On Hold
  },
  {
    id: 2,
    designationName: 'Marketing Manager',
    jobType: 'Part-time',
    vacancyPositions: 2,
    numberOfOpenings: 2,
    branch: 'Marketing',
    grade: 'C',
    band: 'Band2',
    noOfFilledPositions: 6,
    noOfApplicants: 56,
    shortlisted: 22,
    city: 'San Francisco',
    experience: 5,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-30',
    contactPerson: 'Jane Smith',
    status: 'On Hold'
  },
  {
    id: 3,
    designationName: 'Data Scientist',
    jobType: 'Full-time',
    vacancyPositions: 2,
    numberOfOpenings: 3,
    branch: 'Data Analytics',
    grade: 'A',
    band: 'Band4',
    noOfFilledPositions: 8,
    noOfApplicants: 69,
    shortlisted: 42,
    city: 'Los Angeles',
    experience: 4,
    createdAt: '2024-02-01',
    updatedAt: '2024-03-01',
    contactPerson: 'Emily Zhang',
    status: 'Open'
  },
  {
    id: 4,
    designationName: 'HR Specialist',
    jobType: 'Full-time',
    vacancyPositions: 2,
    numberOfOpenings: 1,
    branch: 'Human Resources',
    grade: 'B',
    band: 'Band1',
    noOfFilledPositions: 1,
    noOfApplicants: 65,
    shortlisted: 33,
    city: 'Chicago',
    experience: 3,
    createdAt: '2024-02-15',
    updatedAt: '2024-03-15',
    contactPerson: 'Michael Johnson',
    status: 'Closed'
  },
  {
    id: 5,
    designationName: 'Sales Executive',
    jobType: 'Full-time',
    vacancyPositions: 2,
    numberOfOpenings: 4,
    branch: 'Sales',
    grade: 'B',
    band: 'Band3',
    noOfFilledPositions: 7,
    noOfApplicants: 83,
    shortlisted: 25,
    city: 'Dallas',
    experience: 2,
    createdAt: '2024-01-10',
    updatedAt: '2024-02-10',
    contactPerson: 'Sarah Williams',
    status: 'On Hold'
  },
  {
    id: 6,
    designationName: 'Product Manager',
    jobType: 'Full-time',
    vacancyPositions: 2,
    numberOfOpenings: 2,
    branch: 'Product Development',
    grade: 'C',
    band: 'Band2',
    noOfFilledPositions: 3,
    noOfApplicants: 70,
    shortlisted: 40,
    city: 'Austin',
    experience: 5,
    createdAt: '2024-01-25',
    updatedAt: '2024-02-25',
    contactPerson: 'David Lee',
    status: 'Open'
  }
]
