export const vacancyList = {
  status: 'Success',
  message: 'Branch Bucket fetched successfully',
  totalCount: 14, // Updated to reflect the actual number of items
  data: [
    {
      id: 1,
      designation: 'Software Engineer',
      openings: 3,
      businessRole: 'Development',
      experienceMin: 2,
      experienceMax: 5,
      campusOrlateral: 'Lateral',
      employeeCategory: 'Technical',
      employeeType: 'Full-Time',
      hiringManager: 'John Doe',
      startingDate: '2025-04-01',
      closingDate: '2025-05-01',
      company: 'TechCorp',
      businessUnit: 'IT',
      department: 'Engineering',
      territory: 'North America',
      zone: 'East',
      region: 'Northeast',
      area: 'Metro',
      cluster: 'Cluster A',
      branch: 'New York Branch',
      branchCode: 'NY001',
      city: 'New York',
      state: 'NY',
      origin: 'Internal Posting'
    },
    {
      id: 2,
      designation: 'Product Manager',
      openings: 1,
      businessRole: 'Product',
      experienceMin: 5,
      experienceMax: 10,
      campusOrlateral: 'Lateral',
      employeeCategory: 'Management',
      employeeType: 'Full-Time',
      hiringManager: 'Jane Smith',
      startingDate: '2025-05-15',
      closingDate: '2025-06-15',
      company: 'TechCorp',
      businessUnit: 'Product Development',
      department: 'Product Management',
      territory: 'Europe',
      zone: 'West',
      region: 'Western Europe',
      area: 'Urban',
      cluster: 'Cluster B',
      branch: 'London Branch',
      branchCode: 'LN002',
      city: 'London',
      state: 'England',
      origin: 'External Posting'
    },
    {
      id: 3,
      designation: 'Data Analyst',
      openings: 2,
      businessRole: 'Analytics',
      experienceMin: 1,
      experienceMax: 3,
      campusOrlateral: 'Campus',
      employeeCategory: 'Technical',
      employeeType: 'Contract',
      hiringManager: 'Alice Johnson',
      startingDate: '2025-06-01',
      closingDate: '2025-07-01',
      company: 'DataCorp',
      businessUnit: 'Data Science',
      department: 'Analytics',
      territory: 'Asia',
      zone: 'South',
      region: 'South Asia',
      area: 'Rural',
      cluster: 'Cluster C',
      branch: 'Mumbai Branch',
      branchCode: 'MB003',
      city: 'Mumbai',
      state: 'Maharashtra',
      origin: 'Campus Recruitment'
    },
    {
      id: 4,
      designation: 'HR Specialist',
      openings: 1,
      businessRole: 'Human Resources',
      experienceMin: 3,
      experienceMax: 7,
      campusOrlateral: 'Lateral',
      employeeCategory: 'Administrative',
      employeeType: 'Part-Time',
      hiringManager: 'Robert Brown',
      startingDate: '2025-04-15',
      closingDate: '2025-05-15',
      company: 'PeopleCorp',
      businessUnit: 'HR',
      department: 'Recruitment',
      territory: 'North America',
      zone: 'West',
      region: 'Southwest',
      area: 'Suburban',
      cluster: 'Cluster D',
      branch: 'Los Angeles Branch',
      branchCode: 'LA004',
      city: 'Los Angeles',
      state: 'CA',
      origin: 'Referral'
    },
    {
      id: 5,
      designation: 'Marketing Executive',
      openings: 4,
      businessRole: 'Marketing',
      experienceMin: 0,
      experienceMax: 2,
      campusOrlateral: 'Campus',
      employeeCategory: 'Sales',
      employeeType: 'Full-Time',
      hiringManager: 'Emily Davis',
      startingDate: '2025-07-01',
      closingDate: '2025-08-01',
      company: 'MarketCorp',
      businessUnit: 'Marketing',
      department: 'Digital Marketing',
      territory: 'Australia',
      zone: 'East',
      region: 'Eastern Australia',
      area: 'Metro',
      cluster: 'Cluster E',
      branch: 'Sydney Branch',
      branchCode: 'SY005',
      city: 'Sydney',
      state: 'NSW',
      origin: 'Campus Drive'
    },
    {
      id: 6,
      designation: 'DevOps Engineer',
      openings: 2,
      businessRole: 'Operations',
      experienceMin: 4,
      experienceMax: 8,
      campusOrlateral: 'Lateral',
      employeeCategory: 'Technical',
      employeeType: 'Full-Time',
      hiringManager: 'Michael Lee',
      startingDate: '2025-05-01',
      closingDate: '2025-06-01',
      company: 'TechCorp',
      businessUnit: 'IT',
      department: 'Infrastructure',
      territory: 'South America',
      zone: 'North',
      region: 'Northern South America',
      area: 'Urban',
      cluster: 'Cluster F',
      branch: 'Sao Paulo Branch',
      branchCode: 'SP006',
      city: 'Sao Paulo',
      state: 'SP',
      origin: 'Job Board'
    },
    {
      id: 7,
      designation: 'UX Designer',
      openings: 2,
      businessRole: 'Design',
      experienceMin: 3,
      experienceMax: 6,
      campusOrlateral: 'Lateral',
      employeeCategory: 'Creative',
      employeeType: 'Full-Time',
      hiringManager: 'Sarah Wilson',
      startingDate: '2025-06-15',
      closingDate: '2025-07-15',
      company: 'DesignCorp',
      businessUnit: 'UI/UX',
      department: 'Design',
      territory: 'North America',
      zone: 'Central',
      region: 'Midwest',
      area: 'Urban',
      cluster: 'Cluster G',
      branch: 'Chicago Branch',
      branchCode: 'CH007',
      city: 'Chicago',
      state: 'IL',
      origin: 'External Posting'
    },
    {
      id: 8,
      designation: 'Sales Manager',
      openings: 1,
      businessRole: 'Sales',
      experienceMin: 7,
      experienceMax: 12,
      campusOrlateral: 'Lateral',
      employeeCategory: 'Management',
      employeeType: 'Full-Time',
      hiringManager: 'David Kim',
      startingDate: '2025-05-01',
      closingDate: '2025-06-01',
      company: 'SalesCorp',
      businessUnit: 'Sales',
      department: 'Business Development',
      territory: 'Europe',
      zone: 'North',
      region: 'Northern Europe',
      area: 'Metro',
      cluster: 'Cluster H',
      branch: 'Stockholm Branch',
      branchCode: 'ST008',
      city: 'Stockholm',
      state: 'Stockholm County',
      origin: 'Referral'
    },
    {
      id: 9,
      designation: 'Quality Assurance Engineer',
      openings: 3,
      businessRole: 'Testing',
      experienceMin: 2,
      experienceMax: 5,
      campusOrlateral: 'Lateral',
      employeeCategory: 'Technical',
      employeeType: 'Contract',
      hiringManager: 'Lisa Chen',
      startingDate: '2025-07-01',
      closingDate: '2025-08-01',
      company: 'TechCorp',
      businessUnit: 'Quality Assurance',
      department: 'Testing',
      territory: 'Asia',
      zone: 'East',
      region: 'East Asia',
      area: 'Suburban',
      cluster: 'Cluster I',
      branch: 'Tokyo Branch',
      branchCode: 'TK009',
      city: 'Tokyo',
      state: 'Tokyo',
      origin: 'Job Board'
    },
    {
      id: 10,
      designation: 'Finance Analyst',
      openings: 1,
      businessRole: 'Finance',
      experienceMin: 4,
      experienceMax: 8,
      campusOrlateral: 'Lateral',
      employeeCategory: 'Administrative',
      employeeType: 'Full-Time',
      hiringManager: 'Mark Taylor',
      startingDate: '2025-04-20',
      closingDate: '2025-05-20',
      company: 'FinanceCorp',
      businessUnit: 'Finance',
      department: 'Accounting',
      territory: 'Australia',
      zone: 'West',
      region: 'Western Australia',
      area: 'Rural',
      cluster: 'Cluster J',
      branch: 'Perth Branch',
      branchCode: 'PR010',
      city: 'Perth',
      state: 'WA',
      origin: 'Internal Posting'
    },
    {
      id: 11,
      designation: 'Network Engineer',
      openings: 2,
      businessRole: 'Infrastructure',
      experienceMin: 3,
      experienceMax: 7,
      campusOrlateral: 'Lateral',
      employeeCategory: 'Technical',
      employeeType: 'Full-Time',
      hiringManager: 'Priya Patel',
      startingDate: '2025-06-10',
      closingDate: '2025-07-10',
      company: 'TechCorp',
      businessUnit: 'IT',
      department: 'Networking',
      territory: 'South America',
      zone: 'South',
      region: 'Southern South America',
      area: 'Metro',
      cluster: 'Cluster K',
      branch: 'Buenos Aires Branch',
      branchCode: 'BA011',
      city: 'Buenos Aires',
      state: 'Buenos Aires',
      origin: 'External Posting'
    },
    {
      id: 12,
      designation: 'Content Writer',
      openings: 2,
      businessRole: 'Content',
      experienceMin: 1,
      experienceMax: 4,
      campusOrlateral: 'Campus',
      employeeCategory: 'Creative',
      employeeType: 'Part-Time',
      hiringManager: 'Olivia Green',
      startingDate: '2025-08-01',
      closingDate: '2025-09-01',
      company: 'MediaCorp',
      businessUnit: 'Marketing',
      department: 'Content Creation',
      territory: 'North America',
      zone: 'South',
      region: 'Southeast',
      area: 'Urban',
      cluster: 'Cluster L',
      branch: 'Atlanta Branch',
      branchCode: 'AT012',
      city: 'Atlanta',
      state: 'GA',
      origin: 'Campus Recruitment'
    },
    {
      id: 13,
      designation: 'Security Analyst',
      openings: 1,
      businessRole: 'Security',
      experienceMin: 5,
      experienceMax: 10,
      campusOrlateral: 'Lateral',
      employeeCategory: 'Technical',
      employeeType: 'Full-Time',
      hiringManager: 'James Carter',
      startingDate: '2025-05-15',
      closingDate: '2025-06-15',
      company: 'SecureCorp',
      businessUnit: 'Cybersecurity',
      department: 'Security Operations',
      territory: 'Europe',
      zone: 'East',
      region: 'Eastern Europe',
      area: 'Suburban',
      cluster: 'Cluster M',
      branch: 'Warsaw Branch',
      branchCode: 'WR013',
      city: 'Warsaw',
      state: 'Masovia',
      origin: 'Job Board'
    },
    {
      id: 14,
      designation: 'Customer Support Lead',
      openings: 3,
      businessRole: 'Support',
      experienceMin: 2,
      experienceMax: 6,
      campusOrlateral: 'Lateral',
      employeeCategory: 'Administrative',
      employeeType: 'Full-Time',
      hiringManager: 'Sophie Adams',
      startingDate: '2025-07-15',
      closingDate: '2025-08-15',
      company: 'ServiceCorp',
      businessUnit: 'Customer Service',
      department: 'Support',
      territory: 'Asia',
      zone: 'North',
      region: 'North Asia',
      area: 'Metro',
      cluster: 'Cluster N',
      branch: 'Seoul Branch',
      branchCode: 'SL014',
      city: 'Seoul',
      state: 'Seoul',
      origin: 'Referral'
    }
  ],
  page: 1,
  limit: 10
}
