export const vacancyList = [
  {
    id: 1,
    designation: 'Software Engineer',
    openings: 3,
    businessRole: 'Development',
    experienceMin: 2,
    experienceMax: 5,
    campusOrlateral: 'Lateral',
    employeeCategory: 'Technical',
    employeeType: 'Full-Time',
    hiringManager: 'John Doe',
    startingDate: '2025-04-01',
    closingDate: '2025-05-01',
    company: 'TechCorp',
    businessUnit: 'IT',
    department: 'Engineering',
    territory: 'North America',
    zone: 'East',
    region: 'Northeast',
    area: 'Metro',
    cluster: 'Cluster A',
    branch: 'New York Branch',
    branchCode: 'NY001',
    city: 'New York',
    state: 'NY',
    origin: 'Internal Posting'
  },
  {
    id: 2,
    designation: 'Product Manager',
    openings: 1,
    businessRole: 'Product',
    experienceMin: 5,
    experienceMax: 10,
    campusOrlateral: 'Lateral',
    employeeCategory: 'Management',
    employeeType: 'Full-Time',
    hiringManager: 'Jane Smith',
    startingDate: '2025-05-15',
    closingDate: '2025-06-15',
    company: 'TechCorp',
    businessUnit: 'Product Development',
    department: 'Product Management',
    territory: 'Europe',
    zone: 'West',
    region: 'Western Europe',
    area: 'Urban',
    cluster: 'Cluster B',
    branch: 'London Branch',
    branchCode: 'LN002',
    city: 'London',
    state: 'England',
    origin: 'External Posting'
  },
  {
    id: 3,
    designation: 'Data Analyst',
    openings: 2,
    businessRole: 'Analytics',
    experienceMin: 1,
    experienceMax: 3,
    campusOrlateral: 'Campus',
    employeeCategory: 'Technical',
    employeeType: 'Contract',
    hiringManager: 'Alice Johnson',
    startingDate: '2025-06-01',
    closingDate: '2025-07-01',
    company: 'DataCorp',
    businessUnit: 'Data Science',
    department: 'Analytics',
    territory: 'Asia',
    zone: 'South',
    region: 'South Asia',
    area: 'Rural',
    cluster: 'Cluster C',
    branch: 'Mumbai Branch',
    branchCode: 'MB003',
    city: 'Mumbai',
    state: 'Maharashtra',
    origin: 'Campus Recruitment'
  },
  {
    id: 4,
    designation: 'HR Specialist',
    openings: 1,
    businessRole: 'Human Resources',
    experienceMin: 3,
    experienceMax: 7,
    campusOrlateral: 'Lateral',
    employeeCategory: 'Administrative',
    employeeType: 'Part-Time',
    hiringManager: 'Robert Brown',
    startingDate: '2025-04-15',
    closingDate: '2025-05-15',
    company: 'PeopleCorp',
    businessUnit: 'HR',
    department: 'Recruitment',
    territory: 'North America',
    zone: 'West',
    region: 'Southwest',
    area: 'Suburban',
    cluster: 'Cluster D',
    branch: 'Los Angeles Branch',
    branchCode: 'LA004',
    city: 'Los Angeles',
    state: 'CA',
    origin: 'Referral'
  },
  {
    id: 5,
    designation: 'Marketing Executive',
    openings: 4,
    businessRole: 'Marketing',
    experienceMin: 0,
    experienceMax: 2,
    campusOrlateral: 'Campus',
    employeeCategory: 'Sales',
    employeeType: 'Full-Time',
    hiringManager: 'Emily Davis',
    startingDate: '2025-07-01',
    closingDate: '2025-08-01',
    company: 'MarketCorp',
    businessUnit: 'Marketing',
    department: 'Digital Marketing',
    territory: 'Australia',
    zone: 'East',
    region: 'Eastern Australia',
    area: 'Metro',
    cluster: 'Cluster E',
    branch: 'Sydney Branch',
    branchCode: 'SY005',
    city: 'Sydney',
    state: 'NSW',
    origin: 'Campus Drive'
  },
  {
    id: 6,
    designation: 'DevOps Engineer',
    openings: 2,
    businessRole: 'Operations',
    experienceMin: 4,
    experienceMax: 8,
    campusOrlateral: 'Lateral',
    employeeCategory: 'Technical',
    employeeType: 'Full-Time',
    hiringManager: 'Michael Lee',
    startingDate: '2025-05-01',
    closingDate: '2025-06-01',
    company: 'TechCorp',
    businessUnit: 'IT',
    department: 'Infrastructure',
    territory: 'South America',
    zone: 'North',
    region: 'Northern South America',
    area: 'Urban',
    cluster: 'Cluster F',
    branch: 'Sao Paulo Branch',
    branchCode: 'SP006',
    city: 'Sao Paulo',
    state: 'SP',
    origin: 'Job Board'
  }
]

// Optional: Log the data to verify
console.log(vacancyList)
