export default [
  {
    employeeCode: 'EMP001',
    employmentStatus: 'Approval Pending',
    employmentType: 'Full-time',
    title: 'Mr.',
    employeeName: 'John Doe',
    company: 'ABC Corp',
    department: 'IT',
    territory: 'North Zone',
    zone: 'Zone A',
    region: 'Region 1',
    area: 'Area 5',
    cluster: 'Cluster X',
    branch: 'Main Branch',
    branchCode: 'BR001',
    cityClassification: 'Metro',
    state: 'California',
    personalEmail: 'johndoe@example.com',
    officeEmail: 'johnd@abccorp.com',
    groupDOJ: '2015-06-15',
    designation: 'Software Engineer',
    employeeCategory: 'Technical',
    employeeType: 'Permanent',
    noticePeriod: '30 days',
    mobileNumber: '+1-234-567-8901',
    dateOfResignation: '2024-12-01',
    lastWorkingDay: '2025-01-01',
    additionalDetails: 'Relocating to another city for personal reasons.',
    requestType: 'Resignation',
    approvalStatus: 'pending',
    band: 'B1',
    grade: 'G1',
    bubblePositionsCount: 4,
    bubblePositionBranchIds: ['BRNCH-P001', 'BRNCH-P002', 'BRNCH-P003', 'BRNCH-P003']
  },
  {
    employeeCode: 'EMP001',
    employmentStatus: 'Approval Pending',
    employmentType: 'Full-time',
    title: 'Mr.',
    employeeName: 'John Doe',
    company: 'ABC Corp',
    department: 'IT',
    territory: 'North Zone',
    zone: 'Zone A',
    region: 'Region 1',
    area: 'Area 5',
    cluster: 'Cluster X',
    branch: 'Main Branch',
    branchCode: 'BR001',
    cityClassification: 'Metro',
    state: 'California',
    personalEmail: 'johndoe@example.com',
    officeEmail: 'johnd@abccorp.com',
    groupDOJ: '2015-06-15',
    designation: 'Software Engineer',
    employeeCategory: 'Technical',
    employeeType: 'Permanent',
    noticePeriod: '30 days',
    mobileNumber: '+1-234-567-8901',
    dateOfResignation: '2024-12-01',
    lastWorkingDay: '2025-01-01',
    additionalDetails: 'Relocating to another city for personal reasons.',
    requestType: 'Resignation',
    approvalStatus: 'pending',
    band: 'B1',
    grade: 'G1',
    bubblePositionsCount: 5,
    bubblePositionBranchIds: ['BRNCH-P001', 'BRNCH-P002', 'BRNCH-P003']
  },
  {
    employeeCode: 'EMP001',
    employmentStatus: 'Approval Pending',
    employmentType: 'Full-time',
    title: 'Mr.',
    employeeName: 'John Doe',
    company: 'ABC Corp',
    department: 'IT',
    territory: 'North Zone',
    zone: 'Zone A',
    region: 'Region 1',
    area: 'Area 5',
    cluster: 'Cluster X',
    branch: 'Main Branch',
    branchCode: 'BR001',
    cityClassification: 'Metro',
    state: 'California',
    personalEmail: 'johndoe@example.com',
    officeEmail: 'johnd@abccorp.com',
    groupDOJ: '2015-06-15',
    designation: 'Software Engineer',
    employeeCategory: 'Technical',
    employeeType: 'Permanent',
    noticePeriod: '30 days',
    mobileNumber: '+1-234-567-8901',
    dateOfResignation: '2024-12-01',
    lastWorkingDay: '2025-01-01',
    additionalDetails: 'Relocating to another city for personal reasons.',
    requestType: 'Manual Request',
    approvalStatus: 'pending',
    band: 'B1',
    grade: 'G1',
    bubblePositionsCount: 6,
    bubblePositionBranchIds: ['BRNCH-P001', 'BRNCH-P002', 'BRNCH-P003']
  },
  {
    employeeCode: 'EMP001',
    employmentStatus: 'Approval Pending',
    employmentType: 'Full-time',
    title: 'Mr.',
    employeeName: 'John Doe',
    company: 'ABC Corp',
    department: 'IT',
    territory: 'North Zone',
    zone: 'Zone A',
    region: 'Region 1',
    area: 'Area 5',
    cluster: 'Cluster X',
    branch: 'Main Branch',
    branchCode: 'BR001',
    cityClassification: 'Metro',
    state: 'California',
    personalEmail: 'johndoe@example.com',
    officeEmail: 'johnd@abccorp.com',
    groupDOJ: '2015-06-15',
    designation: 'Software Engineer',
    employeeCategory: 'Technical',
    employeeType: 'Permanent',
    noticePeriod: '30 days',
    mobileNumber: '+1-234-567-8901',
    dateOfResignation: '2024-12-01',
    lastWorkingDay: '2025-01-01',
    additionalDetails: 'Relocating to another city for personal reasons.',
    requestType: 'Resignation',
    approvalStatus: 'pending',
    band: 'B1',
    grade: 'G1',
    bubblePositionsCount: 7,
    bubblePositionBranchIds: ['BRNCH-P001', 'BRNCH-P002', 'BRNCH-P003']
  },
  {
    employeeCode: 'EMP001',
    employmentStatus: 'Approval Pending',
    employmentType: 'Full-time',
    title: 'Mr.',
    employeeName: 'John Doe',
    company: 'ABC Corp',
    department: 'IT',
    territory: 'North Zone',
    zone: 'Zone A',
    region: 'Region 1',
    area: 'Area 5',
    cluster: 'Cluster X',
    branch: 'Main Branch',
    branchCode: 'BR001',
    cityClassification: 'Metro',
    state: 'California',
    personalEmail: 'johndoe@example.com',
    officeEmail: 'johnd@abccorp.com',
    groupDOJ: '2015-06-15',
    designation: 'Software Engineer',
    employeeCategory: 'Technical',
    employeeType: 'Permanent',
    noticePeriod: '30 days',
    mobileNumber: '+1-234-567-8901',
    dateOfResignation: '2024-12-01',
    lastWorkingDay: '2025-01-01',
    additionalDetails: 'Relocating to another city for personal reasons.',
    requestType: 'Bucket Expansion',
    approvalStatus: 'pending',
    band: 'B1',
    grade: 'G1',
    bubblePositionsCount: 10,
    bubblePositionBranchIds: ['BRNCH-P001', 'BRNCH-P002', 'BRNCH-P003']
  },
  {
    employeeCode: 'EMP002',
    employmentStatus: 'Approval Pending',
    employmentType: 'Part-time',
    title: 'Ms.',
    employeeName: 'Jane Smith',
    company: 'XYZ Ltd',
    department: 'HR',
    territory: 'South Zone',
    zone: 'Zone B',
    region: 'Region 2',
    area: 'Area 3',
    cluster: 'Cluster Y',
    branch: 'City Branch',
    branchCode: 'BR002',
    cityClassification: 'Urban',
    state: 'Texas',
    personalEmail: 'janesmith@example.com',
    officeEmail: 'jane.smith@xyzltd.com',
    dateOfJoining: '2018-03-12',
    groupDOJ: '2018-03-12',
    designation: 'HR Manager',
    employeeCategory: 'Administrative',
    employeeType: 'Contract',
    noticePeriod: '15 days',
    mobileNumber: '+1-345-678-9012',
    dateOfResignation: '2024-11-20',
    lastWorkingDay: '2024-12-05',
    additionalDetails: 'Pursuing further education.',
    requestType: 'Resignation',
    band: 'B1',
    grade: 'G1',
    bubblePositionsCount: 8,
    bubblePositionBranchIds: ['BRNCH-P004', 'BRNCH-P005']
  },
  {
    employeeCode: 'EMP003',
    employmentStatus: 'Approved',
    employmentType: 'Full-time',
    title: 'Dr.',
    employeeName: 'Alice Brown',
    company: 'LMN Tech',
    department: 'R&D',
    territory: 'East Zone',
    zone: 'Zone C',
    region: 'Region 3',
    area: 'Area 7',
    cluster: 'Cluster Z',
    branch: 'Innovation Center',
    branchCode: 'BR003',
    cityClassification: 'Urban',
    state: 'Texas',
    personalEmail: 'janesmith@example.com',
    officeEmail: 'jane.smith@xyzltd.com',
    dateOfJoining: '2018-03-12',
    groupDOJ: '2018-03-12',
    designation: 'HR Manager',
    employeeCategory: 'Administrative',
    employeeType: 'Contract',
    noticePeriod: '15 days',
    mobileNumber: '+1-345-678-9012',
    dateOfResignation: '2024-11-20',
    lastWorkingDay: '2024-12-05',
    additionalDetails: 'Working on cutting-edge AI projects.',
    band: 'B2',
    grade: 'G2',
    bubblePositionsCount: 5,
    bubblePositionBranchIds: ['BRNCH-P006', 'BRNCH-P007']
  },
  {
    employeeCode: 'EMP004',
    employmentStatus: 'Approved',
    employmentType: 'Part-time',
    title: 'Mr.',
    employeeName: 'Michael Lee',
    company: 'PQR Inc',
    department: 'Finance',
    territory: 'West Zone',
    zone: 'Zone D',
    region: 'Region 4',
    area: 'Area 2',
    cluster: 'Cluster Q',
    branch: 'Corporate Office',
    branchCode: 'BR004',
    cityClassification: 'Metro',
    state: 'Texas',
    personalEmail: 'janesmith@example.com',
    officeEmail: 'jane.smith@xyzltd.com',
    dateOfJoining: '2018-03-12',
    groupDOJ: '2018-03-12',
    designation: 'HR Manager',
    employeeCategory: 'Administrative',
    employeeType: 'Contract',
    noticePeriod: '15 days',
    mobileNumber: '+1-345-678-9012',
    dateOfResignation: '2024-11-20',
    lastWorkingDay: '2024-12-05',
    additionalDetails: 'Specializes in corporate budgeting and analysis.',
    band: 'B1',
    grade: 'G1',
    bubblePositionsCount: 6,
    bubblePositionBranchIds: ['BRNCH-P008', 'BRNCH-P009']
  },
  {
    employeeCode: 'EMP005',
    employmentStatus: 'Rejected',
    employmentType: 'Full-time',
    title: 'Mrs.',
    employeeName: 'Emily Clark',
    company: 'EFG Solutions',
    department: 'Operations',
    territory: 'Central Zone',
    zone: 'Zone E',
    region: 'Region 5',
    area: 'Area 9',
    cluster: 'Cluster T',
    branch: 'Operations HQ',
    branchCode: 'BR005',
    cityClassification: 'Semi-Urban',
    state: 'Illinois',
    personalEmail: 'emilyclark@example.com',
    officeEmail: 'emily.clark@efgsolutions.com',
    dateOfJoining: '2017-03-05',
    groupDOJ: '2017-03-05',
    designation: 'Operations Manager',
    employeeCategory: 'Technical',
    employeeType: 'Permanent',
    noticePeriod: '30 days',
    dateOfResignation: '2024-10-15',
    lastWorkingDay: '2024-11-15',
    additionalDetails: 'Left to focus on family commitments.',
    band: 'B2',
    grade: 'G2',
    bubblePositionsCount: 12,
    bubblePositionBranchIds: ['BRNCH-P010', 'BRNCH-P011']
  },
  {
    employeeCode: 'EMP006',
    employmentStatus: 'Approved',
    employmentType: 'Full-time',
    title: 'Mrs.',
    employeeName: 'Catherine Green',
    company: 'XYZ Ltd',
    department: 'IT',
    territory: 'South Zone',
    zone: 'Zone B',
    region: 'Region 2',
    area: 'Area 4',
    cluster: 'Cluster Y',
    branch: 'South Branch',
    branchCode: 'BR006',
    cityClassification: 'Urban',
    state: 'Florida',
    personalEmail: 'catherine.green@example.com',
    officeEmail: 'c.green@xyzltd.com',
    dateOfJoining: '2019-02-10',
    groupDOJ: '2019-02-10',
    designation: 'Software Engineer',
    employeeCategory: 'Technical',
    employeeType: 'Permanent',
    noticePeriod: '60 days',
    mobileNumber: '+1-456-789-1234',
    dateOfResignation: '2025-01-10',
    lastWorkingDay: '2025-03-11',
    additionalDetails: 'Switching to a new company for better career prospects.',
    band: 'B1',
    grade: 'G1',
    bubblePositionsCount: 7,
    bubblePositionBranchIds: ['BRNCH-P012', 'BRNCH-P013']
  }
]
