export const interviewCandidates = [
  {
    id: '1',
    candidateName: 'John Doe',
    email: 'john.doe@example.com',
    mobileNumber: '+1234567890',
    designationApplied: 'Software Engineer',
    screeningStatus: 'Shortlisted',
    interviewDate: '2025-05-10T00:00:00Z',
    resumeUrl: 'https://example.com/resumes/john_doe.pdf',
    round1Status: 'Completed',
    round1Feedback: 'Good technical knowledge, confident communicator.',
    round2Status: 'Pending',
    round2Feedback: '',
    aptitudeTestStatus: 'Pass',
    aptitudeTestResultUrl: 'https://example.com/results/john_doe_aptitude.pdf',
    preOfferDocuments: [
      { name: 'ID Proof', url: 'https://example.com/docs/john_doe_id.pdf' },
      { name: 'Certificate', url: 'https://example.com/docs/john_doe_cert.pdf' }
    ],
    proposedSalary: '$80,000',
    negotiationHistory: [
      { date: '2025-05-12', salary: '$75,000', notes: 'Initial offer' },
      { date: '2025-05-14', salary: '$80,000', notes: 'Candidate requested higher salary' }
    ],
    offerLetterUrl: '',
    profileComplete: 85,
    profileMatchPercent: 92,
    source: 'LinkedIn',
    sourceDetails: 'Found via LinkedIn job posting'
  },
  {
    id: '2',
    candidateName: 'Jane Smith',
    email: 'jane.smith@example.com',
    mobileNumber: '+1987654321',
    designationApplied: 'Product Manager',
    screeningStatus: 'Pending',
    interviewDate: '2025-05-11T00:00:00Z',
    resumeUrl: 'https://example.com/resumes/jane_smith.pdf',
    round1Status: 'Pending',
    round2Status: 'Pending',
    aptitudeTestStatus: 'NA',
    preOfferDocuments: [],
    proposedSalary: '$90,000',
    negotiationHistory: [],
    offerLetterUrl: '',
    profileComplete: 70,
    profileMatchPercent: 88,
    source: 'Referral',
    sourceDetails: 'Referred by Sarah Johnson'
  },
  {
    id: '3',
    candidateName: 'Alice Johnson',
    email: 'alice.johnson@example.com',
    mobileNumber: '+1123456789',
    designationApplied: 'UI/UX Designer',
    screeningStatus: 'Rejected',
    interviewDate: '2025-05-12T00:00:00Z',
    resumeUrl: 'https://example.com/resumes/alice_johnson.pdf',
    round1Status: 'Completed',
    round1Feedback: 'Lacks experience in advanced design tools.',
    round2Status: 'Pending',
    aptitudeTestStatus: 'Fail',
    preOfferDocuments: [],
    proposedSalary: '$65,000',
    offerLetterUrl: '',
    profileComplete: 60,
    profileMatchPercent: 75,
    source: 'Job Board',
    sourceDetails: 'Applied via Indeed'
  },
  {
    id: '4',
    candidateName: 'Bob Wilson',
    email: 'bob.wilson@example.com',
    mobileNumber: '+1098765432',
    designationApplied: 'Data Analyst',
    screeningStatus: 'Interviewed',
    interviewDate: '2025-05-13T00:00:00Z',
    resumeUrl: 'https://example.com/resumes/bob_wilson.pdf',
    round1Status: 'Completed',
    round2Status: 'Completed',
    round2Feedback: 'Strong analytical skills, good fit for the team.',
    aptitudeTestStatus: 'Pass',
    preOfferDocuments: [],
    proposedSalary: '$70,000',
    offerLetterUrl: 'https://example.com/offers/bob_wilson_offer.pdf',
    profileComplete: 95,
    profileMatchPercent: 90,
    source: 'Company Website',
    sourceDetails: 'Applied via careers page'
  },
  {
    id: '5',
    candidateName: 'Emma Brown',
    email: 'emmabrown@ex.com',
    mobileNumber: '+1345678901',
    designationApplied: 'DevOps Engineer',
    screeningStatus: 'Shortlisted',
    interviewDate: '2025-05-14T00:00:00Z',
    resumeUrl: 'https://example.com/resumes/emma_brown.pdf',
    round1Status: 'Pending',
    round2Status: 'Pending',
    aptitudeTestStatus: 'NA',
    preOfferDocuments: [],
    proposedSalary: '$85,000',
    offerLetterUrl: '',
    profileComplete: 80,
    profileMatchPercent: 87,
    source: 'LinkedIn',
    sourceDetails: 'Found via LinkedIn job posting'
  },
  {
    id: '6',
    candidateName: 'Michael Lee',
    email: 'michael.lee@example.com',
    mobileNumber: '+1789012345',
    designationApplied: 'QA Engineer',
    screeningStatus: 'Pending',
    interviewDate: '2025-05-15T00:00:00Z',
    resumeUrl: 'https://example.com/resumes/michael_lee.pdf',
    round1Status: 'Pending',
    round2Status: 'Pending',
    aptitudeTestStatus: 'NA',
    preOfferDocuments: [],
    proposedSalary: '$60,000',
    offerLetterUrl: '',
    profileComplete: 65,
    profileMatchPercent: 82,
    source: 'Referral',
    sourceDetails: 'Referred by Mark Wilson'
  },
  {
    id: '7',
    candidateName: 'Sarah Davis',
    email: 'sarah.davis@example.com',
    mobileNumber: '+1567890123',
    designationApplied: 'Backend Developer',
    screeningStatus: 'Rejected',
    interviewDate: '2025-05-16T00:00:00Z',
    resumeUrl: 'https://example.com/resumes/sarah_davis.pdf',
    round1Status: 'Completed',
    round1Feedback: 'Needs improvement in system design.',
    round2Status: 'Pending',
    aptitudeTestStatus: 'Fail',
    preOfferDocuments: [],
    proposedSalary: '$75,000',
    offerLetterUrl: '',
    profileComplete: 55,
    profileMatchPercent: 70,
    source: 'Job Board',
    sourceDetails: 'Applied via Naukri'
  }
]
