// Mock Data
export const mockBudgetData = [
  {
    id: 1,
    jobTitle: 'Software Engineer',
    noOfOpenings: 3,
    grade: 'G1',
    designation: 'Senior Developer',
    businessRole: 'Technical Lead',
    experienceMin: 5,
    experienceMax: 10,
    campusLateral: 'Lateral',
    employeeCategory: 'Permanent',
    employeeType: 'Full-Time',
    hiringManager: 'John Doe',
    startDate: '2025-04-01',
    closingDate: '2025-06-30',
    company: 'Tech Corp',
    businessUnit: 'Engineering',
    department: 'Development',
    territory: 'Territory 1',
    zone: 'Zone 1',
    region: 'Region 1',
    area: 'Area 1',
    cluster: 'Cluster 1',
    branch: 'Branch 1',
    branchCode: 'BR001',
    cityClassification: 'Metro',
    state: 'California',
    budgetDepartment: 'Development',
    position: 'Senior Developer',
    count: 3,
    yearOfBudget: '2025',
    status: 'Approve'
  },
  {
    id: 2,
    jobTitle: 'Product Manager',
    noOfOpenings: 2,
    grade: 'G2',
    designation: 'Product Lead',
    businessRole: 'Product Strategy',
    experienceMin: 7,
    experienceMax: 12,
    campusLateral: 'Campus',
    employeeCategory: 'Contract',
    employeeType: 'Part-Time',
    hiringManager: 'Jane Smith',
    startDate: '2025-05-01',
    closingDate: '2025-07-31',
    company: 'Tech Corp',
    businessUnit: 'Product',
    department: 'Product Management',
    territory: 'Territory 2',
    zone: 'Zone 2',
    region: 'Region 2',
    area: 'Area 2',
    cluster: 'Cluster 2',
    branch: 'Branch 2',
    branchCode: 'BR002',
    cityClassification: 'Non-Metro',
    state: 'Texas',
    budgetDepartment: 'Product Management',
    position: 'Product Lead',
    count: 2,
    yearOfBudget: '2025',
    status: 'Pending'
  },
  {
    id: 3,
    jobTitle: 'Sales Lead',
    noOfOpenings: 3,
    grade: 'G3',
    designation: 'Team Lead',
    businessRole: 'Operations',
    experienceMin: 4,
    experienceMax: 8,
    campusLateral: 'Lateral',
    employeeCategory: 'Permanent',
    employeeType: 'Full-Time',
    hiringManager: 'Alice Johnson',
    startDate: '2025-03-15',
    closingDate: '2025-05-15',
    company: 'Tech Corp',
    businessUnit: 'Sales',
    department: 'Sales',
    territory: 'Territory 3',
    zone: 'Zone 3',
    region: 'Region 3',
    area: 'Area 3',
    cluster: 'Cluster 3',
    branch: 'Branch 3',
    branchCode: 'BR003',
    cityClassification: 'Metro',
    state: 'New York',
    budgetDepartment: 'Sales',
    position: 'Team Lead',
    count: 3,
    yearOfBudget: '2025',
    status: 'Reject'
  }
]
