export const jobs = [
  {
    id: 1,
    title: 'Software Engineer',
    experience: '3+ years',
    description: 'Develop and maintain web applications using React and Node.js.',
    location: 'Kochi, Bengaluru, Thiruvananthapuram',
    job_type: 'Remote',
    job_placement: 'Full-Time',
    skills: ['ERP', 'python', 'openrep', 'development'],
    education: 'BTech/BSc/MCA',
    salary_range: '4 to 5 LPA',
    job_role: 'Jr. Software Engineer'
  },
  {
    id: 2,
    title: 'Project Manager',
    experience: '5+ years',
    description: 'Manage teams and deliver projects on time and budget.',
    location: 'Mumbai, Pune, Hyderabad',
    job_type: 'Onsite',
    job_placement: 'Part-Time',
    skills: ['ERP', 'python', 'openrep', 'development'],
    education: 'Bcom/Mcom/MBA',
    salary_range: '5 to 7 LPA',
    job_role: 'Asst. Project Manager'
  },
  {
    id: 3,
    title: 'UI/UX Designer',
    experience: '2+ years',
    description: 'Design intuitive user interfaces and enhance user experiences.',
    location: 'Delhi, Gurugram, Noida',
    job_type: 'Remote',
    job_placement: 'Full-Time',
    skills: ['ERP', 'python', 'openrep', 'development'],
    education: 'BTech/BSc/MCA',
    salary_range: '3 to 4 LPA',
    job_role: 'Senior UI/UX Designer'
  },
  {
    id: 4,
    title: 'Data Scientist',
    experience: '4+ years',
    description:
      'As a member of the software engineering division, you will take an active role in the definition and evolution of standard practices and procedures. You will be responsible for defining and developing software for tasks associated with the developing, designing and debugging of software applications or operating systems.',
    location: 'Chennai, Coimbatore, Bengaluru',
    job_type: 'Onsite',
    job_placement: 'Part-Time',
    skills: ['ERP', 'python', 'openrep', 'development'],
    education: 'BTech/BSc/MCA',
    salary_range: '7 to 9 LPA',
    job_role: 'Senior Data Scientist'
  },
  {
    id: 5,
    title: 'Software Engineer',
    experience: '3+ years',
    description: 'Develop and maintain web applications using React and Node.js.',
    location: 'Ahmedabad, Surat, Vadodara',
    job_type: 'Remote',
    job_placement: 'Full-Time',
    skills: ['ERP', 'python', 'openrep', 'development'],
    education: 'BTech/BSc/MCA',
    salary_range: '5 to 7 LPA',
    job_role: 'Sr. Software Engineer'
  },
  {
    id: 6,
    title: 'Project Manager',
    experience: '5+ years',
    description: 'Manage teams and deliver projects on time and budget.',
    location: 'Kolkata, Bhubaneswar, Guwahati',
    job_type: 'Onsite',
    job_placement: 'Part-Time',
    skills: ['ERP', 'python', 'openrep', 'development'],
    education: 'Bcom/Mcom/MBA',
    salary_range: '2 to 4 LPA',
    job_role: 'Jr. Project Manager'
  },
  {
    id: 7,
    title: 'UI/UX Designer',
    experience: '2+ years',
    description: 'Design intuitive user interfaces and enhance user experiences.',
    location: 'Lucknow, Kanpur, Varanasi',
    job_type: 'Remote',
    job_placement: 'Full-Time',
    skills: ['ERP', 'python', 'openrep', 'development'],
    education: 'BTech/BSc/MCA',
    salary_range: '3 to 4 LPA',
    job_role: 'Sr. UI/UX designer'
  },
  {
    id: 8,
    title: 'Data Scientist',
    experience: '4+ years',
    description: 'Analyze complex datasets and build predictive models.',
    location: 'Indore, Bhopal, Raipur',
    job_type: 'Onsite',
    job_placement: 'Part-Time',
    skills: ['ERP', 'python', 'openrep', 'development'],
    education: 'BTech/BSc/MCA',
    salary_range: '7 to 9 LPA',
    job_role: 'Sr. Data Scientist'
  },
  {
    id: 9,
    title: 'Software Engineer',
    experience: '3+ years',
    description: 'Develop and maintain web applications using React and Node.js.',
    location: 'Jaipur, Jodhpur, Udaipur',
    job_type: 'Remote',
    job_placement: 'Full-Time',
    skills: ['ERP', 'python', 'openrep', 'development'],
    education: 'BTech/BSc/MCA',
    salary_range: '4 to 5 LPA',
    job_role: 'Jr. Software Engineer'
  },
  {
    id: 10,
    title: 'Project Manager',
    experience: '5+ years',
    description: 'Manage teams and deliver projects on time and budget.',
    location: 'Patna, Ranchi, Jamshedpur',
    job_type: 'Onsite',
    job_placement: 'Part-Time',
    skills: ['ERP', 'python', 'openrep', 'development'],
    education: 'Bcom/Mcom/MBA',
    salary_range: '5 to 7 LPA',
    job_role: 'Sr. Software Engineer'
  },
  {
    id: 11,
    title: 'UI/UX Designer',
    experience: '2+ years',
    description: 'Design intuitive user interfaces and enhance user experiences.',
    location: 'Goa, Panaji, Vasco da Gama',
    job_type: 'Remote',
    job_placement: 'Full-Time',
    skills: ['ERP', 'python', 'openrep', 'development'],
    education: 'BTech/BSc/MCA',
    salary_range: '3 to 4 LPA',
    job_role: 'Sr. Designer'
  },
  {
    id: 12,
    title: 'Data Scientist',
    experience: '4+ years',
    description: 'Analyze complex datasets and build predictive models.',
    location: 'Chandigarh, Mohali, Zirakpur',
    job_type: 'Onsite',
    job_placement: 'Part-Time',
    skills: ['ERP', 'python', 'openrep', 'development'],
    education: 'BTech/BSc/MCA',
    salary_range: '7 to 9 LPA',
    job_role: 'Sr. UI/UX designer'
  }
]
